# Generated by Django 4.1.7 on 2023-05-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_post_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile',
        ),
    ]
