# Generated by Django 4.1.7 on 2023-05-23 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='established',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
