# Generated by Django 4.1.7 on 2023-05-23 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_friend_established'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('user2', 'user1')},
        ),
    ]
