# Generated by Django 4.1.7 on 2023-05-23 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_reposted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replied_to_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_post', to='base.post'),
        ),
    ]
